use std::env;
use std::fs;
use std::path::PathBuf;

const WORKSPACE_CRATES: &[&str] = &[
    "gitrun-core",
    "gitrun-recovery",
    "gitrun-cli",
    "gitrun-gsr",
    "gitrun-scheduler",
    "gitrun-setup",
    "gitrun-updater",
    "gitrun-vault",
    "gitrun-exe",
    "gitrun-dashboard-tauri",
];

fn package_metadata(path: &PathBuf) -> Result<(String, String), String> {
    let content = fs::read_to_string(path)
        .map_err(|error| format!("unable to read {}: {error}", path.display()))?;

    let mut in_package = false;
    let mut name = None;
    let mut version = None;

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') {
            in_package = trimmed == "[package]";
            continue;
        }
        if !in_package {
            continue;
        }

        if let Some(value) = trimmed.strip_prefix("name = \\"") {
            name = value.strip_suffix('"').map(str::to_owned);
        } else if let Some(value) = trimmed.strip_prefix("version = \\"") {
            version = value.strip_suffix('"').map(str::to_owned);
        }

        if name.is_some() && version.is_some() {
            break;
        }
    }

    match (name, version) {
        (Some(name), Some(version)) => Ok((name, version)),
        _ => Err(format!(
            "Cargo.toml at {} has no complete [package] name/version",
            path.display()
        )),
    }
}

fn main() {
    let manifest_dir = PathBuf::from(
        env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set"),
    );
    let workspace_root = manifest_dir
        .parent()
        .and_then(|path| path.parent())
        .expect("gitrun-cli must live two levels below the workspace root");

    let mut versions = Vec::with_capacity(WORKSPACE_CRATES.len());
    for crate_name in WORKSPACE_CRATES {
        let manifest = if *crate_name == "gitrun-dashboard-tauri" {
            workspace_root.join("crates/gitrun-dashboard-tauri/src-tauri/Cargo.toml")
        } else {
            workspace_root.join(format!("crates/{crate_name}/Cargo.toml"))
        };

        println!("cargo:rerun-if-changed={}", manifest.display());

        let (name, version) =
            package_metadata(&manifest).unwrap_or_else(|error| panic!("{error}"));
        if name != *crate_name {
            panic!(
                "expected workspace crate {crate_name}, found package {name} in {}",
                manifest.display()
            );
        }
        versions.push((name, version));
    }

    versions.sort_by(|left, right| left.0.cmp(&right.0));

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR must be set"));
    let output = out_dir.join("gitrun_crate_versions.rs");

    let mut generated = String::from(
        "/// Generated by crates/gitrun-cli/build.rs; do not edit manually.\n",
    );
    generated.push_str("const GITRUN_CRATE_VERSIONS: &[(&str, &str)] = &[\n");
    for (name, version) in versions {
        generated.push_str(&format!("    (\"{name}\", \"{version}\"),\n"));
    }
    generated.push_str("];\n");

    fs::write(&output, generated)
        .unwrap_or_else(|error| panic!("unable to write {}: {error}", output.display()));
}
